name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install Black
        run: pip install black pytest
      - name: Run black --check .
        run: black --check .
      - name: Test with pytest
        run: pytest -v
